[param.gain]
type = "float"
default = 0.006
min = 0.0001
max = 500.0
speed = 0.8
logarithmic = true

[param.crepuscularFalloff]
type = "float"
default = 0.973
min = 0.0001
max = 1.0
speed = 0.0008
logarithmic = true
